from __future__ import annotations

import re

# Multi-word phrase checks for lowercased thread text.
RISK_KEYWORDS = [
    "meet up",
    "meet me",
    "lets meet",
    "let's meet",
    "pick you up",
    "pick u up",
    "come over",
    "come to my",
    "your house",
    "your home",
    "where do you live",
    "what school",
    "which school",
    "alone together",
    "just us",
    "when nobody",
    "when no one is",
    "sneak out",
    "run away",
    "leave your parents",
    "dont tell",
    "do not tell",
    "have to tell anyone",
    "have to tell anybody",
    "dont have to tell",
    "nobody needs to know",
    "no one needs to know",
    "dont let",
    "keep this secret",
    "our secret",
    "stay quiet",
    "delete the chat",
    "clear your history",
    "how old",
    "years old",
    "underage",
    "minor",
    "middle school",
    "high school freshman",
    "too young",
    "webcam",
    "facetime",
    "video call",
    "screen record",
    "screenshot this",
    "live pic",
    "mirror pic",
    "body shot",
    "shirtless",
    "in your underwear",
    "take it off",
    "turn around",
    "pose for",
    "phone number",
    "your number",
    "text me",
    "whatsapp",
    "telegram",
    "discord",
    "instagram",
    "snapchat",
    "add my snap",
    "kik",
    "wickr",
    "email me",
    "drop your @",
    "nude",
    "nudes",
    "naked",
    "nsfw",
    "dick pic",
    "send me a pic",
    "send pic",
    "send photo",
    "show me your",
    "flash me",
    "touch yourself",
    "moan for",
    "turn you on",
    "lose your virginity",
    "first time sex",
    "gift card",
    "venmo",
    "paypal",
    "cashapp",
    "send money",
    "ill buy you",
    "i'll buy you",
    "allowance",
    "if you send",
    "nobody understands",
    "only i understand",
    "special friendship",
    "mature for your age",
    "act older",
    "if you love me",
    "prove you love",
    "dont you trust",
    "don't you trust",
    "hurt my feelings",
    "ill leave",
    "i'll leave",
    "uncomfortable",
    "my parents",
    "tell my mum",
    "tell my mom",
    "tell my dad",
    "going to report",
    "block you",
    "kill yourself",
    "kys",
    "hurt yourself",
    "cut yourself",
]

# Short tokens that must match at word boundaries.
RISK_KEYWORDS_BOUNDARY = [
    "alone",
    "secret",
    "pics",
    "picture",
    "photo",
    "snap",
    "address",
    "young",
    "rape",
    "porn",
]

GROOMING_PHRASES = [
    "just me and you",
    "dont tell anybody",
    "don't tell anybody",
    "dont tell anyone",
    "don't tell anyone",
    "have to tell anyone",
    "have to tell anybody",
    "dont have to tell",
    "don't have to tell",
    "nobody has to know",
    "nobody will know",
    "our little secret",
    "between us",
    "not a big deal if",
    "won't tell anyone",
    "wont tell anyone",
    "chebs",
    "send nudes",
    "send noodz",
    "lewd",
    "horny for you",
    "jerk off",
    "suck my",
    "blow me",
    "finger you",
    "eat you out",
    "get you pregnant",
    "hello beautiful",
    "hey beautiful",
    "hi beautiful",
    "youre beautiful",
    "you're beautiful",
    "prettier than girls",
    "special girl",
    "special boy",
    "boyfriend material",
    "like a girlfriend",
    "older guys",
    "older man",
    "experienced guy",
    "when they are asleep",
    "when parents sleep",
    "after your parents",
    "lock your door",
    "dont wake",
    "skip class",
    "fake sick",
    "disappearing message",
    "vanish mode",
    "burner phone",
    "alt account",
    "finsta",
    "private story",
]

THREAT_PHRASES = [
    "bomb the",
    "going to bomb",
    "blow up the",
    "blow up a",
    "blow up the school",
    "school shooting",
    "shoot up the",
    "active shooter",
    "mass shooting",
    "terrorist",
    "terror attack",
    "detonate",
    "shoot the president",
    "kill the president",
    "attack the capital",
    "attack parliament",
    "attack the government",
    "martyr operation",
    "jihad",
    "infidel",
    "kill everyone",
    "die for the cause",
    "stab you",
    "stab them",
    "kill you",
    "murder you",
    "kidnap",
    "chloroform",
    "pipe bomb",
    "molotov",
    "run them over",
    "rape you",
    "rape her",
    "rape him",
    "anthrax",
    "ricin",
    "sarin",
    "chemical weapon",
    "biological weapon",
    "hostage",
    "execute the",
    "behead",
    "lynch",
    "genocide",
    "ethnic cleansing",
]

THREAT_REGEX = [
    re.compile(r"\bgoing\s+to\s+bomb\b", re.I),
    re.compile(r"\bbomb\s+the\s+\w+", re.I),
    re.compile(r"\b(i\s+will|i'm\s+going\s+to|we\s+will)\s+.*\bbomb\b", re.I),
    re.compile(r"\battack\s+the\s+(capital|city|parliament|government)\b", re.I),
    re.compile(r"\b(shoot|stab|kill)\s+(you|them|him|her|everyone)\b", re.I),
    re.compile(r"\b(i'll|i\s+will)\s+\w*\s*(kill|hurt|shoot|stab)\b", re.I),
]

RE_COME_ON = re.compile(r"\bcome on\b", re.I)

AGE_CUE_PATTERNS = [
    re.compile(r"\bhow\s+old\s+are\s+you\b", re.I),
    re.compile(r"\b(i am|i'm|im)\s+\d{1,2}\b", re.I),
    re.compile(r"\bare\s+you\s+\d{1,2}\b", re.I),
    re.compile(r"\b(i'm|i am|im)\s+only\s+\d{1,2}\b", re.I),
    re.compile(r"\b(i'm|i am|im)\s+a\s+\d{1,2}\s+year\s+old\b", re.I),
    re.compile(r"\byears?\s+old\b", re.I),
    re.compile(r"\bin\s+\d{1,2}(st|nd|rd|th)?\s+grade\b", re.I),
    re.compile(r"\bgrade\s+\d{1,2}\b", re.I),
]

# Parent-aware statements that should lower boundary concern.
PROSOCIAL_PARENT_PHRASES = (
    "let me tell my parents",
    "gonna tell my parents",
    "going to tell my parents",
    "ill tell my parents",
    "ive told my parents",
    "told my parents",
    "telling my parents",
    "ask my parents",
    "asked my parents",
    "asking my parents",
    "check with my parents",
    "checking with my parents",
    "run it by my parents",
    "parents said",
    "parents say",
    "my mom said",
    "my dad said",
    "they said its fine",
    "they said ok",
    "they said yes",
    "theyre ok with",
    "they are ok with",
)

BOUNDARY_WORRY_PARENT_PHRASES = (
    "my parents wouldnt",
    "my parents wont",
    "my parents wouldnt like",
    "my parents dont know",
    "my parents dont like",
    "if my parents",
    "parents would be mad",
    "parents cant know",
    "without my parents knowing",
    "parents would kill",
    "parents wouldnt approve",
    "scared of my parents",
)

RE_MINOR_AGE_STATEMENT = re.compile(r"\b(i\s*am|im)\s+(1[0-7]|[1-9])\b", re.I)
RE_ADULT_AGE_STATEMENT = re.compile(r"\b(i\s*am|im)\s+(1[8-9]|[2-9][0-9])\b", re.I)
